#!/usr/bin/env bash

# give sudo permission for mightybuilder user
# user creation is postponed to the entrypoint,
# so we can create a user with the same id as the host
echo 'mightybuilder ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Install tini
TINI_VERSION="v0.19.0"
curl -Ls https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini -o /opt/docker/bin/tini
chmod +x /opt/docker/bin/tini

# Install recent CMake
CMAKE_RELEASE="3.21.4"
CMAKE_VERSION="3.21"
CMAKE_ARCH="linux-x86_64"
cmake_url="https://cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_RELEASE}-${CMAKE_ARCH}.tar.gz"
target_path="/opt/cmake"
mkdir -p $target_path && \
    curl -Ls $cmake_url | tar -xz -C $target_path --strip-components=1 && \
    export PATH="/opt/cmake/bin:${PATH}" && \
    rm -rf cmake-${CMAKE_RELEASE}-${CMAKE_ARCH}.tar.gz
echo '-- Done with CMake!'

# Install Ninja
Ninja_FILE="ninja-1.10.0.gfb670.kitware.jobserver-1_x86_64-linux-gnu.tar.gz"
Ninja_URL="https://github.com/Kitware/ninja/releases/download/v1.10.0.gfb670.kitware.jobserver-1/ninja-1.10.0.gfb670.kitware.jobserver-1_x86_64-linux-gnu.tar.gz"
target_path="/opt/ninja"
mkdir -p $target_path && \
    curl -Ls $Ninja_URL | tar -xz -C $target_path --strip-components=1 && \
    rm -rf ${Ninja_FILE} && \
    export PATH="/opt/ninja:${PATH}"
echo '-- Done with Ninja!'

# Install the latest Miniconda with Python 3 and update everything.
curl -Ls https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > miniconda.sh && \
    bash miniconda.sh -b -p /opt/conda &> /dev/null && \
    rm miniconda.sh && \
    touch /opt/conda/conda-meta/pinned && \
    export PATH="/opt/conda/bin:${PATH}" && \
    conda config --set show_channel_urls True &> /dev/null && \
    conda config --set always_yes yes &> /dev/null && \
    conda config --set changeps1 no &> /dev/null && \
    conda update --all --yes &> /dev/null && \
    conda clean -tipy &> /dev/null && \
    # Install conda build and deployment tools.
    conda install --yes --quiet conda-build anaconda-client conda-verify jinja2 setuptools &> /dev/null && \
    conda clean -tipsy &> /dev/null
echo '-- Done with Conda!'

# Install Pipenv
pip install --upgrade pip pipenv
echo '-- Done with Pipenv!'

# Create lucky group
groupadd -g 32766 lucky
chgrp -R lucky /opt/conda && chmod -R g=u /opt/conda
